<?php

/**
 * @file
 * Imagefield Zoom module.
 */

/**
 * Implementation of hook_theme().
 */
function imagefield_zoom_theme() {
  return array(
    'imagefield_zoom' => array(
      'variables' => array('images' => NULL),
      'template'  => 'imagefield-zoom',
    ),
  );
}

/**
 * Implements template_preprocess_imagefield_zoom().
 *
 * @param mixed $variables
 *    Variables storage.
 */
function template_preprocess_imagefield_zoom(&$variables) {
  $variables['#attached']['library'][] = 'imagefield_zoom/zoom';
}
