<?php

/**
 * @file
 * Defines a multiple choice quiz field type.
 */

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @return string
 */
function field_quiz_help($route_name) {
  $output = '';
  switch ($route_name) {
    case 'help.page.field_quiz':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Field Quiz module provides a field type for multiple choice questions', array()) . '</p>';
  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function field_quiz_theme() {
  $theme = array(
    'field_quiz_question_view' => array(
      'render element' => 'field_quiz',
      'function' => 'theme_field_quiz_question_view',
    ),
  );
  return $theme;
}


/**
 * Theme the display of the answers and the answer checkboxes.
 *
 * @param $variables
 * @return string
 */
function theme_field_quiz_question_view($variables) {
  $content = '';
  $content .= \Drupal::service('renderer')->render($variables['field_quiz']['#form']);
  return $content;
}