#########################
## Sass Lint File
#########################

# File Options
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'assets/vendors/**/*.*'
    - 'node_modules/**/*.*'
    - 'bower_components/**/*.*'

# Rule Configuration
rules:
  placeholder-in-extend: 0
  no-css-comments: 0
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 5
  border-zero:
    - 1
    - convention: none
  no-ids: 0
  force-element-nesting: 0
  property-sort-order:
    - 1
    - order: smaccs
  class-name-format:
    - 1
    - convention: hyphenatedbem
  variable-name-format:
    - 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  force-attribute-nesting: 0
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
